
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class JFConcurso extends javax.swing.JFrame {
    private Candidato[] candidato;
    private Fiscal[] fiscal;
    private int espec, gerais, contCand, contFisc;
   
    
   
    
    public JFConcurso() {
        initComponents();
        candidato=new Candidato[5];
        fiscal=new Fiscal[5];
        espec = 0;
        gerais=0;
        contCand=0;
        contFisc=0;
        espec=Integer.valueOf(JOptionPane.showInputDialog("Quantidade perguntas especificas:"));
        gerais=Integer.valueOf(JOptionPane.showInputDialog("Quantidade perguntas gerais:"));     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadCand = new javax.swing.JButton();
        btnExibCand = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnCadFisc = new javax.swing.JButton();
        btnExibFiscal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");

        btnCadCand.setText("Cadastrar Candidato");
        btnCadCand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCandActionPerformed(evt);
            }
        });

        btnExibCand.setText("Exibir Candidato");

        btnRanking.setText("Ranking de Candidatos");

        btnCadFisc.setText("Cadastrar Fiscal");
        btnCadFisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFiscActionPerformed(evt);
            }
        });

        btnExibFiscal.setText("Exibir Fiscal");

        jLabel1.setText("Candidatos cadastrados");

        jLabel2.setText("0");

        jLabel3.setText("de 10");

        jLabel4.setText("Fiscais cadastrados");

        jLabel5.setText("0");

        jLabel6.setText("de 10");

        jLabel7.setText("Custos com os fiscais");

        jLabel8.setText("R$ 0");

        jLabel9.setText("Fiscais por sexo ->");

        jLabel10.setText("M:0 | F: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadCand)
                                .addGap(18, 18, 18)
                                .addComponent(btnExibCand))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnCadFisc))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExibFiscal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addComponent(btnRanking)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCand)
                    .addComponent(btnExibCand)
                    .addComponent(btnRanking))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadFisc)
                    .addComponent(btnExibFiscal))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCandActionPerformed
        String nome = " ";
        int idade = 0;
        int especificos;
        int gerais;

        if(contCand<candidato.length){
           nome = JOptionPane.showInputDialog("Digite seu nome");
           idade = Integer.valueOf(JOptionPane.showInputDialog("Digite sua idade: "));
           especificos=Integer.valueOf(JOptionPane.showInputDialog("Digite total de acerto conhecimento: especificos"));
           gerais=Integer.valueOf(JOptionPane.showInputDialog("Digite total de acerto conhecimento: gerais"));
            
           candidato[contCand].cadastrar(nome, idade, especificos, gerais);
           contCand++; 
           
           JOptionPane.showMessageDialog(JFConcurso.this, "Candidato cadastrado com sucesso: ");
           
        }else{
            
        }
        
        
        
    }//GEN-LAST:event_btnCadCandActionPerformed

    private void btnCadFiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFiscActionPerformed
       String nome = " ";
       int idade = 0;
       char sexo;
       double valor=0;
       
       if(contFisc<fiscal.length){
           nome = JOptionPane.showInputDialog("Digite seu nome");
           idade = Integer.valueOf(JOptionPane.showInputDialog("Digite sua idade: "));
           sexo = JOptionPane.showInputDialog("sexo").charAt(0);
           valor = Double.valueOf(JOptionPane.showInputDialog("Informe o salario"));
           
          fiscal[contFisc].cadastrar(nome, idade, sexo, valor);
          contFisc++;
          
          
       }
       
       
       
    }//GEN-LAST:event_btnCadFiscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConcurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadCand;
    private javax.swing.JButton btnCadFisc;
    private javax.swing.JButton btnExibCand;
    private javax.swing.JButton btnExibFiscal;
    private javax.swing.JButton btnRanking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
