
// Generated 06/05/2018 22:57:21 by Hibernate Tools 4.3.1



/**
 * Aluno generated by hbm2java
 */
public class Aluno extends Pessoa {

    
     private String curso;
     private float nota1;
     private float nota2;
     private float media;

  

    public void cadastrar(String curso, float nota1, float nota2, float media) {
        setCurso(curso);
        setNota1(nota1);
        setNota2(nota2);
        setMedia(media);
    }
    
    public void cadastrar(String nome, int idade, String sexo,
                          String curso, float nota1, float nota2, float media){
        super.cadastrar(nome, idade, sexo);
        this.cadastrar(curso, nota1, nota2, media);
    }

    public String getCurso() {
        return curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    public float getNota1() {
        return nota1;
    }

    public void setNota1(float nota1) {
        this.nota1 = nota1;
    }

    public float getNota2() {
        return nota2;
    }

    public void setNota2(float nota2) {
        this.nota2 = nota2;
    }

    public float getMedia() {
        return media;
    }

    public void setMedia(float media) {
        this.media = media;
    }
   
   



}


