
import javax.swing.JInternalFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private Professor[] p;
    private Aluno[] a;
    private Curso[] c;
   
    private int contP;
    private int contA;
    private int contC;
    
    private iFrmCadProfessor cadP;
    private IFrmCadAluno cadA;
    private IFrmCadCurso cadC;
    
    private IFrmExProfessor exP;
    private IFrmExAluno exA;
    private IFrmCadCurso exC;

    private final int TAM_PROF = 5;
    private final int TAM_ALUNO = 10;
    private final int TAM_CURSO = 10;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        p = new Professor[TAM_PROF];
        contP = 0;
        cadP = null;
        
        a = new Aluno[TAM_ALUNO];
        contA = 0;
        cadA=null;
        
        c = new Curso[TAM_CURSO];
        contC = 0;
        cadC = null;
        
        exP=null;
        exA=null;
        exC=null;
    }
    
    public void listar(JInternalFrame x){
        
        if(x instanceof iFrmCadProfessor){
            
            for(int aux = 0; aux < contP;aux++){
                System.out.println(p[aux].exibir());
            }
            
        }else if(x instanceof IFrmCadAluno){
            
            for(int aux = 0; aux < contP;aux++){
                System.out.println(a[aux].exibir());
            } 
           
        }else if(x instanceof IFrmCadCurso){
           for(int aux = 0; aux < contC; aux++){
            System.out.println(c[aux].exibir());
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mniSair = new javax.swing.JMenuItem();
        mnCadastros = new javax.swing.JMenu();
        mniProfessor = new javax.swing.JMenuItem();
        mniAluno = new javax.swing.JMenuItem();
        mniCurso = new javax.swing.JMenuItem();
        mnExibir = new javax.swing.JMenu();
        mniExProfessor = new javax.swing.JMenuItem();
        mniExAluno = new javax.swing.JMenuItem();
        mniExCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema MDI 1");
        setExtendedState(6);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        mnArquivo.setText("Arquivos");

        mniSair.setText("Sair");
        mnArquivo.add(mniSair);

        jMenuBar1.add(mnArquivo);

        mnCadastros.setText("Cadastros");
        mnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrosActionPerformed(evt);
            }
        });

        mniProfessor.setText("Professor");
        mniProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProfessorActionPerformed(evt);
            }
        });
        mnCadastros.add(mniProfessor);

        mniAluno.setText("Aluno");
        mniAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlunoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniAluno);

        mniCurso.setText("Curso");
        mniCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCursoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCurso);

        jMenuBar1.add(mnCadastros);

        mnExibir.setText("Exibir");

        mniExProfessor.setText("Professor");
        mniExProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExProfessorActionPerformed(evt);
            }
        });
        mnExibir.add(mniExProfessor);

        mniExAluno.setText("Aluno");
        mniExAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExAlunoActionPerformed(evt);
            }
        });
        mnExibir.add(mniExAluno);

        mniExCurso.setText("Curso");
        mnExibir.add(mniExCurso);

        jMenuBar1.add(mnExibir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProfessorActionPerformed
        
        p[contP]= new Professor();
        
        cadP = new iFrmCadProfessor(p[contP],this);
        dskPrincipal.add(cadP);
        cadP.setVisible(true);
        
        contP++;      
     
    }//GEN-LAST:event_mniProfessorActionPerformed

    private void mniAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlunoActionPerformed
        
        a[contA]= new Aluno();
        
        
        
        cadA = new IFrmCadAluno(a[contA], c,  contC, this);
        dskPrincipal.add(cadA);
        cadA.setVisible(true);
        
        contA++;

    }//GEN-LAST:event_mniAlunoActionPerformed

    private void mniExProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExProfessorActionPerformed

           exP = new IFrmExProfessor(p, contP);
           dskPrincipal.add(exP);
           exP.setVisible(true);
           

    }//GEN-LAST:event_mniExProfessorActionPerformed

    private void mniExAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExAlunoActionPerformed
        
        exA = new IFrmExAluno(a, contA);
        dskPrincipal.add(exA);
        exA.setVisible(true);
        

    }//GEN-LAST:event_mniExAlunoActionPerformed

    private void mnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrosActionPerformed
        
        
    }//GEN-LAST:event_mnCadastrosActionPerformed

    private void mniCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCursoActionPerformed
        c[contC] = new Curso();
        
        cadC = new IFrmCadCurso(c[contC]);
        dskPrincipal.add(cadC);
        cadC.setVisible(true);
        
        contC++;
    }//GEN-LAST:event_mniCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JMenuItem mniAluno;
    private javax.swing.JMenuItem mniCurso;
    private javax.swing.JMenuItem mniExAluno;
    private javax.swing.JMenuItem mniExCurso;
    private javax.swing.JMenuItem mniExProfessor;
    private javax.swing.JMenuItem mniProfessor;
    private javax.swing.JMenuItem mniSair;
    // End of variables declaration//GEN-END:variables
}
